services:
  backend:
    image: geeksuite/bujogeek:latest
    container_name: bujogeek
    environment:
      - TZ=America/Chicago
      - NODE_ENV=production
      - PORT=5005
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - BASEGEEK_URL=${BASEGEEK_URL}
      - APP_NAME=bujogeek
    ports:
      - "5005:5005"
    volumes:
      - /mnt/Media/Projects/GeekSuite/apps/bujogeek/backend:/app/apps/bujogeek/backend
      - /app/apps/bujogeek/backend/node_modules
      - /app/apps/bujogeek/backend/public
    working_dir: /app/apps/bujogeek/backend
    command: node server.js
    networks:
      - bujogeek_network
    restart: always

#  frontend:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    container_name: bujogeek-frontend
#    environment:
#      - BACKEND_PORT=5005
#    ports:
#      - "9989:80"
#    depends_on:
#      - backend
#    networks:
#      - bujogeek_network
#    restart: always

networks:
  bujogeek_network:
    driver: bridge