services:
  flockgeek:
    image: geeksuite/flockgeek:latest
    container_name: flockgeek
    restart: unless-stopped

    env_file:
      - .env.production

    environment:
      TZ: America/Chicago
      NODE_ENV: production
      PORT: 5001

    ports:
      - "5001:5001"
