/**
 * South-half-of-Arkansas sources + gazetteer (2026-10-10).
 *
 * From five parallel research passes (home counties, central, southwest,
 * southeast/Delta, statewide official). Every feed here was fetched once and
 * returned items; paywalls were checked on one article page (publisher markup
 * `isAccessibleForFree`, Zephr/Piano, CherryRoad and PMPro plugins, "premium
 * content"). Metered counts as paywalled (Chef). Full research, including the
 * dead, hijacked and Facebook-only outlets, is summarised in
 * apps/newsgeek/DOCS/CONTEXT.md.
 *
 * Same insert-if-absent seeding as ./data.js: a deploy adds whatever is missing
 * and never overwrites a row an admin has edited.
 */

const gnews = (q) => `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;
const feed = (url, pollEveryMin, format = 'rss') => ({ url, format, pollEveryMin });
const access = (paywall, content) => ({ paywall, content });
const nws = (zones) => `https://api.weather.gov/alerts/active?zone=${zones.join(',')}`;
const AGG_BLOCKED = ['weather.com'];

export const SOUTH_PLACES = [
  // Counties, south half of Arkansas + central (2026-10-10 source research).
  { slug: 'arkansas-county-ar', name: 'Arkansas County', kind: 'county', parent: 'arkansas', aliases: ['Arkansas Co.'], fips: '05001' },
  { slug: 'ashley-county-ar', name: 'Ashley County', kind: 'county', parent: 'arkansas', aliases: ['Ashley Co.'], fips: '05003' },
  { slug: 'bradley-county-ar', name: 'Bradley County', kind: 'county', parent: 'arkansas', aliases: ['Bradley Co.'], fips: '05011' },
  { slug: 'calhoun-county-ar', name: 'Calhoun County', kind: 'county', parent: 'arkansas', aliases: ['Calhoun Co.'], fips: '05013' },
  { slug: 'chicot-county-ar', name: 'Chicot County', kind: 'county', parent: 'arkansas', aliases: ['Chicot Co.'], fips: '05017' },
  { slug: 'cleveland-county-ar', name: 'Cleveland County', kind: 'county', parent: 'arkansas', aliases: ['Cleveland Co.'], fips: '05025' },
  { slug: 'columbia-county-ar', name: 'Columbia County', kind: 'county', parent: 'arkansas', aliases: ['Columbia Co.'], fips: '05027' },
  { slug: 'dallas-county-ar', name: 'Dallas County', kind: 'county', parent: 'arkansas', aliases: ['Dallas Co.'], fips: '05039' },
  { slug: 'desha-county-ar', name: 'Desha County', kind: 'county', parent: 'arkansas', aliases: ['Desha Co.'], fips: '05041' },
  { slug: 'drew-county-ar', name: 'Drew County', kind: 'county', parent: 'arkansas', aliases: ['Drew Co.'], fips: '05043' },
  { slug: 'faulkner-county-ar', name: 'Faulkner County', kind: 'county', parent: 'arkansas', aliases: ['Faulkner Co.'], fips: '05045' },
  { slug: 'grant-county-ar', name: 'Grant County', kind: 'county', parent: 'arkansas', aliases: ['Grant Co.'], fips: '05053' },
  { slug: 'hempstead-county-ar', name: 'Hempstead County', kind: 'county', parent: 'arkansas', aliases: ['Hempstead Co.'], fips: '05057' },
  { slug: 'howard-county-ar', name: 'Howard County', kind: 'county', parent: 'arkansas', aliases: ['Howard Co.'], fips: '05061' },
  { slug: 'jefferson-county-ar', name: 'Jefferson County', kind: 'county', parent: 'arkansas', aliases: ['Jefferson Co.'], fips: '05069' },
  { slug: 'lafayette-county-ar', name: 'Lafayette County', kind: 'county', parent: 'arkansas', aliases: ['Lafayette Co.'], fips: '05073' },
  { slug: 'lee-county-ar', name: 'Lee County', kind: 'county', parent: 'arkansas', aliases: ['Lee Co.'], fips: '05077' },
  { slug: 'lincoln-county-ar', name: 'Lincoln County', kind: 'county', parent: 'arkansas', aliases: ['Lincoln Co.'], fips: '05079' },
  { slug: 'little-river-county-ar', name: 'Little River County', kind: 'county', parent: 'arkansas', aliases: ['Little River Co.'], fips: '05081' },
  { slug: 'lonoke-county-ar', name: 'Lonoke County', kind: 'county', parent: 'arkansas', aliases: ['Lonoke Co.'], fips: '05085' },
  { slug: 'miller-county-ar', name: 'Miller County', kind: 'county', parent: 'arkansas', aliases: ['Miller Co.'], fips: '05091' },
  { slug: 'monroe-county-ar', name: 'Monroe County', kind: 'county', parent: 'arkansas', aliases: ['Monroe Co.'], fips: '05095' },
  { slug: 'montgomery-county-ar', name: 'Montgomery County', kind: 'county', parent: 'arkansas', aliases: ['Montgomery Co.'], fips: '05097' },
  { slug: 'nevada-county-ar', name: 'Nevada County', kind: 'county', parent: 'arkansas', aliases: ['Nevada Co.'], fips: '05099' },
  { slug: 'ouachita-county-ar', name: 'Ouachita County', kind: 'county', parent: 'arkansas', aliases: ['Ouachita Co.'], fips: '05103' },
  { slug: 'perry-county-ar', name: 'Perry County', kind: 'county', parent: 'arkansas', aliases: ['Perry Co.'], fips: '05105' },
  { slug: 'phillips-county-ar', name: 'Phillips County', kind: 'county', parent: 'arkansas', aliases: ['Phillips Co.'], fips: '05107' },
  { slug: 'pike-county-ar', name: 'Pike County', kind: 'county', parent: 'arkansas', aliases: ['Pike Co.'], fips: '05109' },
  { slug: 'polk-county-ar', name: 'Polk County', kind: 'county', parent: 'arkansas', aliases: ['Polk Co.'], fips: '05113' },
  { slug: 'prairie-county-ar', name: 'Prairie County', kind: 'county', parent: 'arkansas', aliases: ['Prairie Co.'], fips: '05117' },
  { slug: 'pulaski-county-ar', name: 'Pulaski County', kind: 'county', parent: 'arkansas', aliases: ['Pulaski Co.'], fips: '05119' },
  { slug: 'saline-county-ar', name: 'Saline County', kind: 'county', parent: 'arkansas', aliases: ['Saline Co.'], fips: '05125' },
  { slug: 'sevier-county-ar', name: 'Sevier County', kind: 'county', parent: 'arkansas', aliases: ['Sevier Co.'], fips: '05133' },
  { slug: 'union-county-ar', name: 'Union County', kind: 'county', parent: 'arkansas', aliases: ['Union Co.'], fips: '05139' },
  // Towns, each under its county.
  { slug: 'ashdown-ar', name: 'Ashdown', kind: 'town', parent: 'little-river-county-ar', aliases: [] },
  { slug: 'bauxite-ar', name: 'Bauxite', kind: 'town', parent: 'saline-county-ar', aliases: [] },
  { slug: 'benton-ar', name: 'Benton', kind: 'town', parent: 'saline-county-ar', aliases: [] },
  { slug: 'brinkley-ar', name: 'Brinkley', kind: 'town', parent: 'monroe-county-ar', aliases: [] },
  { slug: 'bryant-ar', name: 'Bryant', kind: 'town', parent: 'saline-county-ar', aliases: [] },
  { slug: 'cabot-ar', name: 'Cabot', kind: 'town', parent: 'lonoke-county-ar', aliases: [] },
  { slug: 'camden-ar', name: 'Camden', kind: 'town', parent: 'ouachita-county-ar', aliases: [] },
  { slug: 'clarendon-ar', name: 'Clarendon', kind: 'town', parent: 'monroe-county-ar', aliases: [] },
  { slug: 'conway-ar', name: 'Conway', kind: 'town', parent: 'faulkner-county-ar', aliases: [] },
  { slug: 'crossett-ar', name: 'Crossett', kind: 'town', parent: 'ashley-county-ar', aliases: [] },
  { slug: 'de-queen-ar', name: 'De Queen', kind: 'town', parent: 'sevier-county-ar', aliases: [] },
  { slug: 'dewitt-ar', name: 'DeWitt', kind: 'town', parent: 'arkansas-county-ar', aliases: [] },
  { slug: 'dierks-ar', name: 'Dierks', kind: 'town', parent: 'howard-county-ar', aliases: [] },
  { slug: 'dumas-ar', name: 'Dumas', kind: 'town', parent: 'desha-county-ar', aliases: [] },
  { slug: 'el-dorado-ar', name: 'El Dorado', kind: 'town', parent: 'union-county-ar', aliases: [] },
  { slug: 'eudora-ar', name: 'Eudora', kind: 'town', parent: 'chicot-county-ar', aliases: [] },
  { slug: 'fordyce-ar', name: 'Fordyce', kind: 'town', parent: 'dallas-county-ar', aliases: [] },
  { slug: 'glenwood-ar', name: 'Glenwood', kind: 'town', parent: 'pike-county-ar', aliases: [] },
  { slug: 'greenbrier-ar', name: 'Greenbrier', kind: 'town', parent: 'faulkner-county-ar', aliases: [] },
  { slug: 'hamburg-ar', name: 'Hamburg', kind: 'town', parent: 'ashley-county-ar', aliases: [] },
  { slug: 'hampton-ar', name: 'Hampton', kind: 'town', parent: 'calhoun-county-ar', aliases: [] },
  { slug: 'haskell-ar', name: 'Haskell', kind: 'town', parent: 'saline-county-ar', aliases: [] },
  { slug: 'hazen-ar', name: 'Hazen', kind: 'town', parent: 'prairie-county-ar', aliases: [] },
  { slug: 'helena-west-helena-ar', name: 'Helena-West Helena', kind: 'town', parent: 'phillips-county-ar', aliases: ['Helena', 'West Helena'] },
  { slug: 'hope-ar', name: 'Hope', kind: 'town', parent: 'hempstead-county-ar', aliases: [] },
  { slug: 'horatio-ar', name: 'Horatio', kind: 'town', parent: 'sevier-county-ar', aliases: [] },
  { slug: 'jacksonville-ar', name: 'Jacksonville', kind: 'town', parent: 'pulaski-county-ar', aliases: [] },
  { slug: 'jessieville-ar', name: 'Jessieville', kind: 'town', parent: 'garland-county-ar', aliases: [] },
  { slug: 'junction-city-ar', name: 'Junction City', kind: 'town', parent: 'union-county-ar', aliases: [] },
  { slug: 'lake-hamilton-ar', name: 'Lake Hamilton', kind: 'town', parent: 'garland-county-ar', aliases: [] },
  { slug: 'lake-village-ar', name: 'Lake Village', kind: 'town', parent: 'chicot-county-ar', aliases: [] },
  { slug: 'lewisville-ar', name: 'Lewisville', kind: 'town', parent: 'lafayette-county-ar', aliases: [] },
  { slug: 'little-rock-ar', name: 'Little Rock', kind: 'town', parent: 'pulaski-county-ar', aliases: [] },
  { slug: 'lockesburg-ar', name: 'Lockesburg', kind: 'town', parent: 'sevier-county-ar', aliases: [] },
  { slug: 'lonoke-ar', name: 'Lonoke', kind: 'town', parent: 'lonoke-county-ar', aliases: [] },
  { slug: 'magnolia-ar', name: 'Magnolia', kind: 'town', parent: 'columbia-county-ar', aliases: [] },
  { slug: 'marianna-ar', name: 'Marianna', kind: 'town', parent: 'lee-county-ar', aliases: [] },
  { slug: 'maumelle-ar', name: 'Maumelle', kind: 'town', parent: 'pulaski-county-ar', aliases: [] },
  { slug: 'mayflower-ar', name: 'Mayflower', kind: 'town', parent: 'faulkner-county-ar', aliases: [] },
  { slug: 'mcgehee-ar', name: 'McGehee', kind: 'town', parent: 'desha-county-ar', aliases: [] },
  { slug: 'mena-ar', name: 'Mena', kind: 'town', parent: 'polk-county-ar', aliases: [] },
  { slug: 'monticello-ar', name: 'Monticello', kind: 'town', parent: 'drew-county-ar', aliases: [] },
  { slug: 'mount-ida-ar', name: 'Mount Ida', kind: 'town', parent: 'montgomery-county-ar', aliases: [] },
  { slug: 'mountain-pine-ar', name: 'Mountain Pine', kind: 'town', parent: 'garland-county-ar', aliases: [] },
  { slug: 'murfreesboro-ar', name: 'Murfreesboro', kind: 'town', parent: 'pike-county-ar', aliases: [] },
  { slug: 'nashville-ar', name: 'Nashville', kind: 'town', parent: 'howard-county-ar', aliases: [] },
  { slug: 'norphlet-ar', name: 'Norphlet', kind: 'town', parent: 'union-county-ar', aliases: [] },
  { slug: 'north-little-rock-ar', name: 'North Little Rock', kind: 'town', parent: 'pulaski-county-ar', aliases: ['NLR'] },
  { slug: 'pearcy-ar', name: 'Pearcy', kind: 'town', parent: 'garland-county-ar', aliases: [] },
  { slug: 'perla-ar', name: 'Perla', kind: 'town', parent: 'hot-spring-county-ar', aliases: [] },
  { slug: 'pine-bluff-ar', name: 'Pine Bluff', kind: 'town', parent: 'jefferson-county-ar', aliases: [] },
  { slug: 'poyen-ar', name: 'Poyen', kind: 'town', parent: 'grant-county-ar', aliases: [] },
  { slug: 'prescott-ar', name: 'Prescott', kind: 'town', parent: 'nevada-county-ar', aliases: [] },
  { slug: 'rison-ar', name: 'Rison', kind: 'town', parent: 'cleveland-county-ar', aliases: [] },
  { slug: 'sheridan-ar', name: 'Sheridan', kind: 'town', parent: 'grant-county-ar', aliases: [] },
  { slug: 'sherwood-ar', name: 'Sherwood', kind: 'town', parent: 'pulaski-county-ar', aliases: [] },
  { slug: 'smackover-ar', name: 'Smackover', kind: 'town', parent: 'union-county-ar', aliases: [] },
  { slug: 'stamps-ar', name: 'Stamps', kind: 'town', parent: 'lafayette-county-ar', aliases: [] },
  { slug: 'star-city-ar', name: 'Star City', kind: 'town', parent: 'lincoln-county-ar', aliases: [] },
  { slug: 'stuttgart-ar', name: 'Stuttgart', kind: 'town', parent: 'arkansas-county-ar', aliases: [] },
  { slug: 'texarkana-ar', name: 'Texarkana', kind: 'town', parent: 'miller-county-ar', aliases: [] },
  { slug: 'vilonia-ar', name: 'Vilonia', kind: 'town', parent: 'faulkner-county-ar', aliases: [] },
  { slug: 'waldo-ar', name: 'Waldo', kind: 'town', parent: 'columbia-county-ar', aliases: [] },
  { slug: 'warren-ar', name: 'Warren', kind: 'town', parent: 'bradley-county-ar', aliases: [] },
  { slug: 'whelen-springs-ar', name: 'Whelen Springs', kind: 'town', parent: 'clark-county-ar', aliases: [] },
  { slug: 'white-hall-ar', name: 'White Hall', kind: 'town', parent: 'jefferson-county-ar', aliases: [] },
];

export const SOUTH_SOURCES = [
  {
    slug: 'arkansas-tv', name: 'Arkansas TV (formerly Arkansas PBS)', homepage: 'https://www.arkansastv.gov',
    kind: 'journalism', sections: ['state'], places: ['little-rock-ar', 'pulaski-county-ar', 'arkansas'],
    feeds: [feed('https://www.arkansastv.gov/rss.xml', 60)], access: access('none', 'excerpt'),
    notes: 'Mostly program/promo with some public-affairs (Arkansas Week, debates). arkansaspbs.org is a parked domain; network left PBS.',
  },
  {
    slug: 'ashley-county-ledger', name: 'Ashley County Ledger', homepage: 'https://www.ashleycountyledger.com',
    kind: 'journalism', sections: ['local'], places: ['hamburg-ar', 'ashley-county-ar'],
    feeds: [feed('https://www.ashleycountyledger.com/search/?f=rss&t=article&l=50', 30)], access: access('metered', 'excerpt'),
    notes: 'Hamburg weekly. Feed mixes local and wire/syndicated (national) items; verify metering. Found via APA directory.',
  },
  {
    slug: 'ashley-news-observer', name: 'The Ashley News Observer', homepage: 'https://www.ashleynewsobserver.com',
    kind: 'journalism', sections: ['local'], places: ['crossett-ar', 'hamburg-ar', 'ashley-county-ar'],
    feeds: [feed('https://www.ashleynewsobserver.com/category/news/feed/', 30)], access: access('metered', 'full'),
    notes: 'Use the /category/news/feed/ URL, NOT /feed/: the main feed (newest 2026-10-09) is 10 items of classifieds/e-edition junk. Weekly, ~10 items spans 3 weeks. Same',
  },
  {
    slug: 'chicot-county-spectator', name: 'Chicot County Spectator', homepage: 'https://www.chicotnewspapers.com',
    kind: 'journalism', sections: ['local'], places: ['lake-village-ar', 'eudora-ar', 'chicot-county-ar'],
    feeds: [feed('https://www.chicotnewspapers.com/category/news/feed/', 30)], access: access('metered', 'full'),
    notes: 'chicotspectator.com redirects to chicotnewspapers.com. Use category/news feed; main /feed/ is polluted by classifieds/e-editions (but also carries opinion/colum',
  },
  {
    slug: 'dewitt-era-enterprise', name: 'DeWitt Era-Enterprise', homepage: 'https://www.dewitt-ee.com',
    kind: 'journalism', sections: ['local'], places: ['dewitt-ar', 'stuttgart-ar', 'arkansas-county-ar'],
    feeds: [feed('https://www.dewitt-ee.com/feed.atom', 30, 'atom')], access: access('none', 'full'),
    notes: 'era-enterprise.com is an alias (article links point to www.era-enterprise.com). Rails-based CMS, same platform as Monroe County Argus. Bought July 2024 by new o',
  },
  {
    slug: 'dumas-clarion', name: 'Dumas Clarion', homepage: 'https://www.dumasclarion.com',
    kind: 'journalism', sections: ['local'], places: ['dumas-ar', 'mcgehee-ar', 'desha-county-ar'],
    feeds: [feed('https://www.dumasclarion.com/rss.xml', 30)], access: access('metered', 'excerpt'),
    notes: 'Some stories premium. Feed description is essentially title; fetch for body. Appears to be the only live Desha County paper (McGehee Times domain is parked).',
  },
  {
    slug: 'fordyce-news-advocate', name: 'Fordyce News Advocate', homepage: 'https://fordycenewsadvocate.com',
    kind: 'journalism', sections: ['local'], places: ['fordyce-ar', 'dallas-county-ar'],
    feeds: [feed('https://fordycenewsadvocate.com/feed/', 60)], access: access('none', 'full'),
    notes: 'Low volume, posts in batches (10 items span Aug 3 - Oct 5); category feeds /category/news/feed/ empty, use main feed. Includes South Arkansas/state wire items (',
  },
  {
    slug: 'helena-world', name: 'The Helena World', homepage: 'https://www.helenaworld.org',
    kind: 'journalism', sections: ['local'], places: ['helena-west-helena-ar', 'phillips-county-ar'],
    feeds: [feed('https://www.helenaworld.org/blog-feed.xml', 30)], access: access('none', 'excerpt'),
    notes: 'Wix site. Feed items are description-only; content skews to schools/community. Other domain helena-world.com is a suspended page.',
  },
  {
    slug: 'hope-prescott-news', name: 'Hope-Prescott News', homepage: 'https://hopeprescott.com',
    kind: 'journalism', sections: ['local'], places: ['hope-ar', 'prescott-ar', 'hempstead-county-ar', 'nevada-county-ar'],
    feeds: [feed('https://www.hopeprescott.com/feed/', 30)], access: access('none', 'full'),
    notes: 'Est. 2018 weekly. Found via APA directory.',
  },
  {
    slug: 'ksla', name: 'KSLA 12 (Shreveport)', homepage: 'https://www.ksla.com',
    kind: 'journalism', sections: ['local'], places: ['texarkana-ar', 'miller-county-ar', 'columbia-county-ar', 'lafayette-county-ar', 'union-county-ar'],
    feeds: [feed('https://www.ksla.com/arc/outboundfeeds/rss/category/news/arkansas/?outputType=xml', 60)], access: access('none', 'excerpt'),
    notes: 'Very low Arkansas yield; mostly Louisiana. Candidate only, probably skip or use Arkansas category at 60min.',
  },
  {
    slug: 'ktal-nbc6', name: 'KTAL NBC 6 (Texarkana)', homepage: 'https://www.ktalnews.com',
    kind: 'journalism', sections: ['local'], places: ['texarkana-ar', 'miller-county-ar', 'little-river-county-ar', 'hempstead-county-ar', 'lafayette-county-ar', 'sevier-county-ar', 'howard-county-ar', 'nevada-county-ar', 'columbia-county-ar'],
    feeds: [feed('https://www.ktalnews.com/feed/', 15)], access: access('none', 'excerpt'),
    notes: 'Main feed is mostly Texarkana-area (TX+AR mix) plus video items; category feeds /category/texarkana/ and /category/local/ exist but are empty. Arkansas category',
  },
  {
    slug: 'ktbs', name: 'KTBS 3 (Shreveport)', homepage: 'https://www.ktbs.com',
    kind: 'journalism', sections: ['local'], places: ['texarkana-ar', 'miller-county-ar', 'columbia-county-ar', 'lafayette-county-ar', 'union-county-ar', 'magnolia-ar', 'el-dorado-ar'],
    feeds: [feed('https://www.ktbs.com/search/?f=rss&t=article&l=50&c=news/arkansas', 30)], access: access('none', 'excerpt'),
    notes: 'ArkLaTex station, mostly Louisiana/East Texas. The c=news/arkansas category feed is the useful one (mixes statewide + Texarkana AR). Main feed is mostly Shrevep',
  },
  {
    slug: 'log-cabin-democrat', name: 'Log Cabin Democrat (Conway)', homepage: 'https://www.thecabin.net',
    kind: 'journalism', sections: ['local'], places: ['conway-ar', 'faulkner-county-ar', 'greenbrier-ar', 'vilonia-ar', 'mayflower-ar'],
    feeds: [feed('https://www.thecabin.net/search/?f=rss&t=article&l=50', 15)], access: access('metered', 'excerpt'),
    notes: 'Some items have no description (police beat = one line). Feed link rel=alternate also offers #topstory variant.',
  },
  {
    slug: 'magnolia-reporter', name: 'Magnolia Reporter', homepage: 'https://www.magnoliareporter.com',
    kind: 'journalism', sections: ['local'], places: ['magnolia-ar', 'columbia-county-ar', 'lafayette-county-ar', 'stamps-ar', 'lewisville-ar', 'waldo-ar', 'union-county-ar', 'el-dorado-ar'],
    feeds: [feed('https://www.magnoliareporter.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc', 30)], access: access('none', 'excerpt'),
    notes: 'Independent, free. Feed includes public-records items (marriage licenses, divorce decrees) - noisy but locally relevant. Homepage-advertised feed is the #topsto',
  },
  {
    slug: 'monroe-county-argus', name: 'The Monroe County Argus', homepage: 'https://www.monroecountyargus.com',
    kind: 'journalism', sections: ['local'], places: ['brinkley-ar', 'clarendon-ar', 'monroe-county-ar', 'lee-county-ar'],
    feeds: [feed('https://monroecountyargus.com/feed.atom', 30, 'atom')], access: access('none', 'full'),
    notes: 'Covers Monroe County, with Marianna Trojans sports coverage (Lee County). Same publisher as Helena World per Wikipedia (Helena-West Helena World owners bought M',
  },
  {
    slug: 'monticello-live', name: 'Monticello Live', homepage: 'https://www.monticellolive.com',
    kind: 'journalism', sections: ['local'], places: ['monticello-ar', 'drew-county-ar'],
    feeds: [feed('https://www.monticellolive.com/feed/', 30)], access: access('none', 'full'),
    notes: 'Digital outlet. Found via APA directory.',
  },
  {
    slug: 'my-pulse-news', name: 'My Pulse News (Mena)', homepage: 'https://mypulsenews.com',
    kind: 'journalism', sections: ['local'], places: ['mena-ar', 'polk-county-ar'],
    feeds: [feed('https://mypulsenews.com/feed/', 60)], access: access('none', 'full'),
    notes: 'Mena/Polk County. Heavy on police reports and sheriff\'s logs. Low cadence (~weekly), so 60-min poll; close to stale threshold at 8 days. Polk County mentions 27',
  },
  {
    slug: 'obu-signal', name: 'The OBU Signal', homepage: 'https://www.obusignal.com',
    kind: 'journalism', sections: ['local'], places: ['arkadelphia-ar', 'clark-county-ar'],
    feeds: [feed('https://www.obusignal.com/feed/', 60)], access: access('none', 'full'),
    notes: 'Ouachita Baptist student paper (www.obusignal.com, separate from Cloudflare-blocked obu.edu). Campus/lifestyle skew, mostly features not hard news; academic-yea',
  },
  {
    slug: 'pine-bluff-commercial', name: 'Pine Bluff Commercial', homepage: 'https://www.pbcommercial.com',
    kind: 'journalism', sections: ['local'], places: ['pine-bluff-ar', 'jefferson-county-ar', 'white-hall-ar'],
    feeds: [feed('https://www.pbcommercial.com/feed/', 30)], access: access('none', 'full'),
    notes: 'Main /feed/ returns ~389 items back to 2026-08-26 (large payload; dedupe on guid). Use /category/news/feed/ if payload is a concern. /rss also works.',
  },
  {
    slug: 'saline-courier', name: 'Saline Courier (Benton)', homepage: 'https://www.bentoncourier.com',
    kind: 'journalism', sections: ['local'], places: ['benton-ar', 'bryant-ar', 'bauxite-ar', 'haskell-ar', 'saline-county-ar'],
    feeds: [feed('https://www.bentoncourier.com/search/?f=rss&t=article&l=50', 30)], access: access('metered', 'excerpt'),
    notes: 'Sports-heavy (Friday football). Covers Bryant.',
  },
  {
    slug: 'sau-news', name: 'Southern Arkansas University News', homepage: 'https://www.saumag.edu/news/',
    kind: 'journalism', sections: ['local'], places: ['magnolia-ar', 'columbia-county-ar'],
    feeds: [feed('https://www.saumag.edu/news/feed/', 60)], access: access('none', 'full'),
    notes: 'University press releases (athletics, rodeo, campus). kind could be \'official\' but treated as newsroom. Student paper The Bray (thebrayonline.com) does not reso',
  },
  {
    slug: 'southwest-arkansas-news', name: 'Southwest Arkansas News (Nashville Leader)', homepage: 'https://swarkansasnews.com',
    kind: 'journalism', sections: ['local'], places: ['nashville-ar', 'howard-county-ar', 'dierks-ar', 'glenwood-ar', 'pike-county-ar', 'murfreesboro-ar'],
    feeds: [feed('https://swarkansasnews.com/feed/', 30)], access: access('none', 'excerpt'),
    notes: 'Appears to be the Nashville Leader successor (home page references Nashville Leader, Howard County). Feed gives title+description excerpt only. PMPro installed ',
  },
  {
    slug: 'stuttgart-daily-leader', name: 'Stuttgart Daily Leader', homepage: 'https://www.stuttgartdailyleader.com',
    kind: 'journalism', sections: ['local'], places: ['stuttgart-ar', 'dewitt-ar', 'arkansas-county-ar'],
    feeds: [feed('https://www.stuttgartdailyleader.com/feed/', 15)], access: access('none', 'excerpt'),
    notes: 'Good volume; sports-heavy (Ricebirds). Excerpt in description.',
  },
  {
    slug: 'ualr-news', name: 'UA Little Rock News', homepage: 'https://ualr.edu/news/',
    kind: 'journalism', sections: ['local'], places: ['little-rock-ar', 'pulaski-county-ar'],
    feeds: [feed('https://ualr.edu/news/feed/', 60)], access: access('none', 'full'),
    notes: 'University PR, not independent newsroom. Student paper not found.',
  },
  {
    slug: 'uams-news', name: 'UAMS News', homepage: 'https://news.uams.edu',
    kind: 'journalism', sections: ['state'], places: ['little-rock-ar', 'pulaski-county-ar', 'arkansas'],
    feeds: [feed('https://news.uams.edu/feed/', 60)], access: access('none', 'full'),
    notes: 'Health system/institution PR; statewide relevance. www.uamshealth.com/news/feed/ is the same content.',
  },
  {
    slug: 'uca-news', name: 'UCA News', homepage: 'https://uca.edu/news/',
    kind: 'journalism', sections: ['local'], places: ['conway-ar', 'faulkner-county-ar'],
    feeds: [feed('https://uca.edu/news/feed/', 60)], access: access('none', 'full'),
    notes: 'University PR. The Echo student paper domain ucaecho.com is parked/for sale.',
  },
  {
    slug: 'agfc-news', name: 'Arkansas Game & Fish Commission', homepage: 'https://www.agfc.com',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://www.agfc.com/feed/', 60)], access: access('none', 'excerpt'),
    notes: 'WordPress. Fishing reports arrive as posts in this same feed. /en/news/feed/ is only a comments feed (0 items).',
  },
  {
    slug: 'ar-ag-news', name: 'Arkansas Attorney General News Releases', homepage: 'https://arkansasag.gov',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://arkansasag.gov/feed/?post_type=news-release', 60)], access: access('none', 'excerpt'),
    notes: 'Consumer alerts, fraud arrests, settlements. Camden-Fairview consent decree item appeared 2026-10-02.',
  },
  {
    slug: 'ar-dps-news', name: 'Arkansas State Police / Public Safety News (incl. ADEM)', homepage: 'https://dps.arkansas.gov/news/',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://dps.arkansas.gov/feed/?post_type=news', 60)], access: access('none', 'excerpt'),
    notes: 'DPS umbrella: ASP releases (arrests, homicides, sentencings, county-tagged in titles) plus Emergency Management (e.g. ShakeOut Day). ADEM site now redirects to ',
  },
  {
    slug: 'ar-governor-news', name: 'Arkansas Governor\'s Office News', homepage: 'https://governor.arkansas.gov',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://governor.arkansas.gov/feed/?post_type=news_post', 60)], access: access('none', 'excerpt'),
    notes: 'Press releases. Also /feed/?post_type=announcements and executive_orders exist (announcements stale, newest 2025-02-07).',
  },
  {
    slug: 'ar-health-news', name: 'Arkansas Department of Health News', homepage: 'https://healthy.arkansas.gov/news',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://healthy.arkansas.gov/feed/?post_type=article', 60)], access: access('none', 'excerpt'),
    notes: 'Flu clinics, health alerts, press releases. Dedupe on first poll. Plain /feed/ is empty.',
  },
  {
    slug: 'ardot-news', name: 'ARDOT news releases', homepage: 'https://ardot.gov/news/',
    kind: 'official', sections: ['state'], places: ['arkansas', 'dallas-county-ar', 'ouachita-county-ar', 'clark-county-ar'],
    feeds: [feed('https://ardot.gov/feed/?post_type=news', 30)], access: access('none', 'full'),
    notes: 'Statewide lane/road closures; needs county text-match (Clark, Hot Spring, Garland, Pike, Montgomery, Dallas; I-30, US 67, US 70, US 270, Hwy 7) to be local. Dis',
  },
  {
    slug: 'arfb-news', name: 'Arkansas Farm Bureau News', homepage: 'https://www.arfb.com/news/',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://www.arfb.com/news/rss/', 60)], access: access('none', 'excerpt'),
    notes: 'Advocacy org (not government); market briefs, harvest updates, ag policy. Marked official only because brief lacks an \'organization\' kind; treat as ag-interest ',
  },
  {
    slug: 'city-of-conway', name: 'City of Conway', homepage: 'https://conwayarkansas.gov',
    kind: 'official', sections: ['local'], places: ['conway-ar', 'faulkner-county-ar'],
    feeds: [feed('https://conwayarkansas.gov/feed/', 60)], access: access('none', 'full'),
    notes: 'Old cityofconway.org no longer resolves; news also at api.conwayarkansas.gov/news.',
  },
  {
    slug: 'city-of-el-dorado', name: 'City of El Dorado News (goeldorado.com)', homepage: 'https://www.goeldorado.com/news/',
    kind: 'official', sections: ['local'], places: ['el-dorado-ar', 'union-county-ar'],
    feeds: [feed('https://www.goeldorado.com/news/feed/', 60)], access: access('none', 'title'),
    notes: 'City-run site (footer: City of El Dorado). Mostly council meeting notices, monthly cadence - low volume.',
  },
  {
    slug: 'city-of-little-rock', name: 'City of Little Rock news', homepage: 'https://www.littlerock.gov',
    kind: 'official', sections: ['local'], places: ['little-rock-ar', 'pulaski-county-ar'],
    feeds: [feed('https://www.littlerock.gov/news/feed/', 60)], access: access('none', 'full'),
    notes: 'Mix of news and meeting notices. /feed/ (10 items) is a similar sitewide feed. Police dept page has no separate feed.',
  },
  {
    slug: 'city-of-maumelle', name: 'City of Maumelle news flash', homepage: 'https://www.maumelle.gov',
    kind: 'official', sections: ['local'], places: ['maumelle-ar', 'pulaski-county-ar'],
    feeds: [feed('https://www.maumelle.gov/RSSFeed.aspx?ModID=1&CID=All-newsflash.xml', 60)], access: access('none', 'excerpt'),
    notes: 'Low volume.',
  },
  {
    slug: 'city-of-north-little-rock', name: 'City of North Little Rock', homepage: 'https://nlr.ar.gov',
    kind: 'official', sections: ['local'], places: ['north-little-rock-ar', 'pulaski-county-ar'],
    feeds: [feed('https://nlr.ar.gov/feed/', 60)], access: access('none', 'full'),
    notes: 'www.nlr.ar.gov also resolves.',
  },
  {
    slug: 'clark-county-ar-gov', name: 'Clark County, Arkansas (county government)', homepage: 'https://clarkcountyar.gov',
    kind: 'official', sections: ['local'], places: ['arkadelphia-ar', 'gurdon-ar', 'caddo-valley-ar', 'amity-ar', 'okolona-ar', 'whelen-springs-ar', 'clark-county-ar'],
    feeds: [feed('https://clarkcountyar.gov/feed/', 60)], access: access('none', 'excerpt'),
    notes: 'NEW host: brief lists county gov sites as dead; clarkcountyar.gov (also served at clarkcountyarkansas.com) works. Very low volume (3 posts total).',
  },
  {
    slug: 'conway-corp', name: 'Conway Corp', homepage: 'https://conwaycorp.com',
    kind: 'official', sections: ['local'], places: ['conway-ar', 'faulkner-county-ar'],
    feeds: [feed('https://conwaycorp.com/feed/', 60)], access: access('none', 'full'),
    notes: 'Mix of outage/service notices and promo.',
  },
  {
    slug: 'entergy-arkansas', name: 'Entergy Arkansas news and blog', homepage: 'https://www.entergy.com/news/arkansas',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://www.entergy.com/tag/arkansas/feed/', 60)], access: access('none', 'excerpt'),
    notes: 'Corporate PR/blog, not outage data (outage map is etrviewoutage.com, no feed). Statewide Arkansas. Storm Center updates are tagged separately and could be a sec',
  },
  {
    slug: 'garland-county-agendas', name: 'Garland County agendas', homepage: 'https://www.garlandcounty.org/AgendaCenter',
    kind: 'official', sections: ['local'], places: ['garland-county-ar', 'hot-springs-ar', 'hot-springs-village-ar', 'lake-hamilton-ar', 'mountain-pine-ar', 'jessieville-ar'],
    feeds: [feed('https://www.garlandcounty.org/RSSFeed.aspx?ModID=65&CID=All-0', 60)], access: access('none', 'title'),
    notes: 'Garland News Flash (ModID=1) and Alert Center (ModID=63, All) feeds are valid but EMPTY (0 items) right now; worth registering later, they carry burn bans/road/',
  },
  {
    slug: 'hot-springs-agendas', name: 'City of Hot Springs agendas', homepage: 'https://www.hotspringsar.gov/AgendaCenter',
    kind: 'official', sections: ['local'], places: ['hot-springs-ar', 'garland-county-ar'],
    feeds: [feed('https://www.hotspringsar.gov/RSSFeed.aspx?ModID=65&CID=All-0', 60)], access: access('none', 'title'),
    notes: 'Brief only lists Hot Springs News Flash as already present; the agenda feed is not (Malvern + Arkadelphia agendas are). Hot Springs Alert Center (ModID=63) and ',
  },
  {
    slug: 'nps-hot-springs', name: 'Hot Springs National Park (NPS news releases)', homepage: 'https://www.nps.gov/hosp/',
    kind: 'official', sections: ['local'], places: ['hot-springs-ar', 'garland-county-ar'],
    feeds: [feed('https://www.nps.gov/feeds/getNewsRSS.htm?id=hosp', 60)], access: access('none', 'excerpt'),
    notes: 'Low volume (~1-2/month). getAlertsRSS and getEventsRSS for id=hosp return 404.',
  },
  {
    slug: 'rock-region-metro', name: 'Rock Region METRO', homepage: 'https://www.rrmetro.org',
    kind: 'official', sections: ['local'], places: ['little-rock-ar', 'north-little-rock-ar', 'pulaski-county-ar'],
    feeds: [feed('https://www.rrmetro.org/feed/', 60)], access: access('none', 'full'),
    notes: '10 items span Feb-Oct 2026 (low volume).',
  },
  {
    slug: 'sau-tech', name: 'SAU Tech News', homepage: 'https://www.sautech.edu',
    kind: 'official', sections: ['local'], places: ['camden-ar', 'ouachita-county-ar'],
    feeds: [feed('https://www.sautech.edu/feed/rss2', 60)], access: access('none', 'excerpt'),
    notes: 'Southern Arkansas University Tech, Camden. Use one of the two feeds, not both. Atom item count not checked.',
  },
  {
    slug: 'seark-news', name: 'Southeast Arkansas College (SEARK) News', homepage: 'https://seark.edu/news',
    kind: 'official', sections: ['local'], places: ['pine-bluff-ar', 'jefferson-county-ar'],
    feeds: [feed('https://seark.edu/rss.xml', 60)], access: access('none', 'excerpt'),
    notes: 'Pine Bluff college; low volume. Drop if Pine Bluff researcher already covers it.',
  },
  {
    slug: 'uaex-news', name: 'UA Division of Agriculture - Extension News', homepage: 'https://www.uaex.uada.edu/media-resources/news/',
    kind: 'official', sections: ['state'], places: ['arkansas'],
    feeds: [feed('https://www.uaex.uada.edu/media-resources/news/feeds/extension-news.xml', 60)], access: access('none', 'excerpt'),
    notes: 'Crop reports, ag research, 4-H. Statewide; county extension offices have no feeds found. www.uada.edu 403s every UA including a browser UA (Cloudflare) - use th',
  },
  {
    slug: 'usace-little-rock-district', name: 'USACE Little Rock District news', homepage: 'https://www.swl.usace.army.mil/Media/News-Releases/',
    kind: 'official', sections: ['local'], places: ['arkadelphia-ar', 'clark-county-ar', 'hot-spring-county-ar', 'garland-county-ar', 'pike-county-ar', 'montgomery-county-ar', 'hot-springs-ar'],
    feeds: [feed('https://www.swl.usace.army.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=441&max=20', 60)], access: access('none', 'excerpt'),
    notes: 'Corps runs DeGray Lake, Lake Ouachita, Lake Greeson, Narrows Dam, Blue Mountain etc. Whole district (all Arkansas), low volume. HTML pages on the same host retu',
  },
  {
    slug: 'nws-central-arkansas', name: 'NWS: central Arkansas', homepage: 'https://www.weather.gov/lzk',
    kind: 'official', sections: ['local'], places: ['garland-county-ar', 'pike-county-ar', 'montgomery-county-ar', 'dallas-county-ar', 'grant-county-ar', 'saline-county-ar', 'pulaski-county-ar', 'faulkner-county-ar', 'lonoke-county-ar', 'perry-county-ar'],
    feeds: [feed(nws(['ARC051', 'ARC109', 'ARC097', 'ARC039', 'ARC053', 'ARC125', 'ARC119', 'ARC045', 'ARC085', 'ARC105', 'ARZ032', 'ARZ039', 'ARZ042', 'ARZ043', 'ARZ044', 'ARZ045', 'ARZ052', 'ARZ055', 'ARZ062', 'ARZ241']), 10, 'nws')], access: access('none', 'excerpt'),
    notes: 'Active alerts. ARC = county zones (warnings), ARZ = forecast zones (watches, advisories), from api.weather.gov/zones.',
  },
  {
    slug: 'nws-southwest-arkansas', name: 'NWS: southwest Arkansas', homepage: 'https://www.weather.gov/shv',
    kind: 'official', sections: ['local'], places: ['miller-county-ar', 'hempstead-county-ar', 'nevada-county-ar', 'howard-county-ar', 'sevier-county-ar', 'little-river-county-ar', 'lafayette-county-ar', 'columbia-county-ar', 'ouachita-county-ar', 'union-county-ar', 'calhoun-county-ar', 'polk-county-ar'],
    feeds: [feed(nws(['ARC091', 'ARC057', 'ARC099', 'ARC061', 'ARC133', 'ARC081', 'ARC073', 'ARC027', 'ARC103', 'ARC139', 'ARC013', 'ARC113', 'ARZ050', 'ARZ051', 'ARZ059', 'ARZ060', 'ARZ061', 'ARZ066', 'ARZ067', 'ARZ070', 'ARZ071', 'ARZ072', 'ARZ073', 'ARZ140', 'ARZ240']), 10, 'nws')], access: access('none', 'excerpt'),
    notes: 'Active alerts. ARC = county zones (warnings), ARZ = forecast zones (watches, advisories), from api.weather.gov/zones.',
  },
  {
    slug: 'nws-southeast-arkansas', name: 'NWS: southeast Arkansas', homepage: 'https://www.weather.gov/jan',
    kind: 'official', sections: ['local'], places: ['arkansas-county-ar', 'ashley-county-ar', 'bradley-county-ar', 'chicot-county-ar', 'cleveland-county-ar', 'desha-county-ar', 'drew-county-ar', 'jefferson-county-ar', 'lee-county-ar', 'lincoln-county-ar', 'monroe-county-ar', 'phillips-county-ar'],
    feeds: [feed(nws(['ARC001', 'ARC003', 'ARC011', 'ARC017', 'ARC025', 'ARC041', 'ARC043', 'ARC069', 'ARC077', 'ARC079', 'ARC095', 'ARC107', 'ARZ047', 'ARZ049', 'ARZ056', 'ARZ057', 'ARZ058', 'ARZ063', 'ARZ064', 'ARZ065', 'ARZ068', 'ARZ069', 'ARZ074', 'ARZ075']), 10, 'nws')], access: access('none', 'excerpt'),
    notes: 'Active alerts. ARC = county zones (warnings), ARZ = forecast zones (watches, advisories), from api.weather.gov/zones.',
  },
  {
    slug: 'gnews-gurdon', name: 'Google News: Gurdon', homepage: 'https://news.google.com',
    kind: 'aggregator', sections: ['local'], places: ['clark-county-ar', 'gurdon-ar'],
    feeds: [feed(gnews('"Gurdon" Arkansas'), 60)], access: access('none', 'title'), blockedDomains: AGG_BLOCKED,
    notes: 'Gap-fill: no free feed of its own. Title-only; credited to the item\'s <source>.',
  },
  {
    slug: 'gnews-hot-springs', name: 'Google News: Hot Springs & Garland County', homepage: 'https://news.google.com',
    kind: 'aggregator', sections: ['local'], places: ['garland-county-ar', 'hot-springs-ar'],
    feeds: [feed(gnews('"Hot Springs" OR "Garland County" Arkansas when:7d'), 60)], access: access('none', 'title'), blockedDomains: AGG_BLOCKED,
    notes: 'Gap-fill: no free feed of its own. Title-only; credited to the item\'s <source>.',
  },
  {
    slug: 'gnews-texarkana', name: 'Google News: Texarkana', homepage: 'https://news.google.com',
    kind: 'aggregator', sections: ['local'], places: ['miller-county-ar', 'texarkana-ar'],
    feeds: [feed(gnews('"Texarkana" Arkansas when:7d'), 60)], access: access('none', 'title'), blockedDomains: AGG_BLOCKED,
    notes: 'Gap-fill: no free feed of its own. Title-only; credited to the item\'s <source>.',
  },
  {
    slug: 'gnews-camden', name: 'Google News: Camden', homepage: 'https://news.google.com',
    kind: 'aggregator', sections: ['local'], places: ['ouachita-county-ar', 'camden-ar'],
    feeds: [feed(gnews('"Camden" Arkansas when:7d'), 60)], access: access('none', 'title'), blockedDomains: AGG_BLOCKED,
    notes: 'Gap-fill: no free feed of its own. Title-only; credited to the item\'s <source>.',
  },
  {
    slug: 'gnews-el-dorado', name: 'Google News: El Dorado', homepage: 'https://news.google.com',
    kind: 'aggregator', sections: ['local'], places: ['union-county-ar', 'el-dorado-ar'],
    feeds: [feed(gnews('"El Dorado" Arkansas when:7d'), 60)], access: access('none', 'title'), blockedDomains: AGG_BLOCKED,
    notes: 'Gap-fill: no free feed of its own. Title-only; credited to the item\'s <source>.',
  },
  {
    slug: 'gnews-hope', name: 'Google News: Hope & Prescott', homepage: 'https://news.google.com',
    kind: 'aggregator', sections: ['local'], places: ['hempstead-county-ar', 'hope-ar', 'nevada-county-ar', 'prescott-ar'],
    feeds: [feed(gnews('"Hope" OR "Prescott" Arkansas when:7d'), 60)], access: access('none', 'title'), blockedDomains: AGG_BLOCKED,
    notes: 'Gap-fill: no free feed of its own. Title-only; credited to the item\'s <source>.',
  },
];

export default { SOUTH_PLACES, SOUTH_SOURCES };
