/**
 * The type icons a household can pick from. A ThingType stores its icon as
 * a name (the starter types use DirectionsBoat, GpsFixed, …); this is the one
 * place a name becomes a glyph. An unknown name falls back to the crate.
 * Every icon here is the MUI "Outlined"/filled family at one weight, so a
 * grid of types never looks like icon soup.
 */
import {
  Agriculture,
  AllInbox,
  Anchor,
  Backpack,
  Bed,
  Blender,
  Carpenter,
  Chair,
  Checkroom,
  Computer,
  Construction,
  Devices,
  Diamond,
  DirectionsBoat,
  DirectionsCar,
  ElectricBolt,
  Garage,
  GpsFixed,
  Handyman,
  Hardware,
  Headphones,
  Hiking,
  Home,
  Inventory2,
  Kayaking,
  Keyboard,
  Kitchen,
  LocalLaundryService,
  LocalShipping,
  Lock,
  Luggage,
  MeetingRoom,
  MenuBook,
  Microwave,
  MusicNote,
  PedalBike,
  Pets,
  PhoneIphone,
  PhotoCamera,
  Piano,
  Place,
  Pool,
  RvHookup,
  Sailing,
  SolarPower,
  Speaker,
  SportsEsports,
  Toys,
  Tv,
  TwoWheeler,
  Warehouse,
  Watch,
  Weekend,
  Yard,
} from '@mui/icons-material';

export const TYPE_ICONS = {
  Inventory2,
  // Where things are: locations and storage.
  Place,
  Home,
  MeetingRoom,
  Garage,
  Warehouse,
  AllInbox,
  Lock,
  DirectionsBoat,
  Sailing,
  Kayaking,
  Anchor,
  DirectionsCar,
  LocalShipping,
  RvHookup,
  TwoWheeler,
  PedalBike,
  GpsFixed,
  Hiking,
  Backpack,
  Handyman,
  Construction,
  Carpenter,
  Hardware,
  Agriculture,
  Yard,
  SolarPower,
  ElectricBolt,
  Devices,
  Computer,
  PhoneIphone,
  Keyboard,
  Headphones,
  Speaker,
  Tv,
  SportsEsports,
  PhotoCamera,
  Watch,
  Diamond,
  Kitchen,
  Microwave,
  Blender,
  LocalLaundryService,
  Chair,
  Weekend,
  Bed,
  Piano,
  MusicNote,
  MenuBook,
  Checkroom,
  Luggage,
  Toys,
  Pets,
  Pool,
};

export const TYPE_ICON_NAMES = Object.keys(TYPE_ICONS);

export const DEFAULT_TYPE_ICON = 'Inventory2';

export function typeIconFor(name) {
  return TYPE_ICONS[name] ?? TYPE_ICONS[DEFAULT_TYPE_ICON];
}
