/**
 * Shared fixtures for the BookGeek web test suite — the same library used by
 * the phone-width screenshot harness (scripts/shoot.mjs / Chef's Goodreads
 * export), so what you see in a review screenshot is what the tests exercise.
 */

export const BOOKS = [
  {
    id: 'b1',
    title: 'Lock In',
    authors: ['John Scalzi'],
    shelf: 'reading',
    rating: 4,
    pageCount: 336,
    publishedDate: '2014-08-26',
    readingProgress: 42,
    tags: ['science fiction', 'mystery'],
    publisher: 'Tor Books',
    isbn: '9780765375865',
    isbn13: null,
    goodreadsId: '21418013',
    language: 'en',
    owned: true,
    description:
      'Fifteen years from now, a new virus sweeps the globe. 95% of those afflicted experience nothing worse than fever and headaches. Four percent suffer acute meningitis. And one percent find themselves &quot;locked in&quot; &mdash; fully awake and aware, but unable to move or respond to stimulus.<br/><br/>A gripping near-future thriller.',
    files: [{ format: 'epub', path: '/data/library/b1.epub', size: 1200000, addedAt: '2026-03-03' }],
    review: '',
    dateAdded: '2026-03-03',
    dateStarted: null,
    dateFinished: null,
    readCount: 0,
    createdAt: '2026-03-03',
    updatedAt: '2026-09-01',
  },
  {
    id: 'b2',
    title: 'The Sound of Gravel',
    authors: ['Ruth Wariner'],
    shelf: 'read',
    rating: 5,
    pageCount: 336,
    publishedDate: '2016-01-05',
    readingProgress: 100,
    tags: ['memoir'],
    publisher: 'Flatiron Books',
    isbn: '9780765375865',
    isbn13: null,
    goodreadsId: '21418013',
    language: 'en',
    owned: true,
    description: 'A memoir of growing up in a polygamist family.',
    files: [{ format: 'epub', path: '/data/library/b2.epub', size: 1200000, addedAt: '2026-03-03' }],
    review: 'Devastating and beautifully written.',
    dateAdded: '2026-03-03',
    dateStarted: '2026-04-01',
    dateFinished: '2026-05-01',
    readCount: 1,
    createdAt: '2026-03-03',
    updatedAt: '2026-09-01',
  },
  {
    id: 'b4',
    title: 'The Road to Jonestown: Jim Jones and Peoples Temple',
    authors: ['Jeff Guinn'],
    shelf: 'want-to-read',
    rating: 0,
    pageCount: 454,
    publishedDate: '2017-04-11',
    readingProgress: 0,
    tags: ['history'],
    publisher: 'Simon & Schuster',
    isbn: '9780765375865',
    isbn13: null,
    goodreadsId: '21418013',
    language: 'en',
    owned: false,
    description: 'The definitive history of Jim Jones and Peoples Temple.',
    files: [],
    review: '',
    dateAdded: '2026-03-03',
    dateStarted: null,
    dateFinished: null,
    readCount: 0,
    createdAt: '2026-03-03',
    updatedAt: '2026-09-01',
  },
  {
    id: 'b5',
    title: "The Dryad's Crown",
    authors: ['David Hopkins'],
    shelf: 'on-reader',
    rating: 5,
    pageCount: 569,
    publishedDate: '2023-03-01',
    readingProgress: 0,
    tags: ['fantasy'],
    publisher: 'Independent',
    isbn: '9780765375865',
    isbn13: null,
    goodreadsId: '21418013',
    language: 'en',
    owned: true,
    description: 'An epic fantasy of gods and dryads.',
    files: [{ format: 'epub', path: '/data/library/b5.epub', size: 1200000, addedAt: '2026-03-03' }],
    review: '',
    dateAdded: '2026-03-03',
    dateStarted: null,
    dateFinished: null,
    readCount: 0,
    createdAt: '2026-03-03',
    updatedAt: '2026-09-01',
  },
];

/** `shelves` prop shape used by BookCard, ShelfStrip, LibraryToolbar, ShelfSheet,
 * DetailHero and SettingsView: `{ id, label }`, "All books" first. */
export const SHELVES = [
  { id: 'all', label: 'All books' },
  { id: 'reading', label: 'Reading' },
  { id: 'on-reader', label: 'On Reader' },
  { id: 'unread', label: 'Unread' },
  { id: 'read', label: 'Read' },
  { id: 'want-to-read', label: 'Want to read' },
  { id: 'abandoned', label: 'Abandoned' },
  { id: 'need-to-find', label: 'Need to find' },
  { id: 'custom-comfort-reads', label: 'Comfort reads' },
];

/** `shelfSummary` shape used by ShelfStrip/navConfig's `shelfCount`. */
export const SHELF_SUMMARY = {
  total: 223,
  owned: 190,
  unowned: 33,
  shelves: [
    { id: 'reading', count: 2 },
    { id: 'on-reader', count: 7 },
    { id: 'unread', count: 61 },
    { id: 'read', count: 118 },
    { id: 'want-to-read', count: 27 },
    { id: 'abandoned', count: 4 },
    { id: 'need-to-find', count: 3 },
    { id: 'custom-comfort-reads', count: 1 },
  ],
};

export const SAVED_FILTERS = [
  { id: 'f1', name: 'Kindle queue', filters: { shelf: 'on-reader' } },
  { id: 'f2', name: 'Unread sci-fi', filters: { shelf: 'unread', tag: 'science fiction' } },
];
